export function getData(filter) {

    const state = {
        allData: [
            {
            ID:'200',
            Comercio: "Shop 200",
            CUIT: '60000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 209,
            Activo: false,
            UltimaVenta: '14/09/1995'
        },
        {
            ID:'202',
            Comercio: "Shop NW",
            CUIT: '10000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 450,
            Activo: false,
            UltimaVenta: '25/02/1995'
        },
        {
            ID:'204',
            Comercio: "Shop XA",
            CUIT: '30000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 605,
            Activo: true,
            UltimaVenta: '4/08/1995'
        },
        {
            ID:'203',
            Comercio: "Shop EW",
            CUIT: '40000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 540,
            Activo: true,
            UltimaVenta: '22/01/1995'
        },
        {
            ID:'205',
            Comercio: "Shop PO",
            CUIT: '52200000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 2300,
            Activo: false,
            UltimaVenta: '11/02/1994'
        },
        {
            ID:'206',
            Comercio: "Shop FD",
            CUIT: '70000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 986,
            Activo: true,
            UltimaVenta: '23/11/1995'
        },
        {
            ID:'207',
            Comercio: "Shop CV",
            CUIT: '88000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1235,
            Activo: true,
            UltimaVenta: '21/07/1995'
        },
        {
            ID:'208',
            Comercio: "Shop LK",
            CUIT: '95000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 732,
            Activo: true,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'209',
            Comercio: "Shop QW",
            CUIT: '50001100',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 913,
            Activo: true,
            UltimaVenta: '01/09/1995'
        },
        {
            ID:'210',
            Comercio: "Shop ZX",
            CUIT: '10040000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 543,
            Activo: false,
            UltimaVenta: '05/09/1995'
        },
        {
            ID:'211',
            Comercio: "Shop BG",
            CUIT: '20001000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 789,
            Activo: false,
            UltimaVenta: '21/01/1995'
        },
        {
            ID:'212',
            Comercio: "Shop RE",
            CUIT: '71000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 111,
            Activo: true,
            UltimaVenta: '08/08/1998'
        },
        {
            ID:'213',
            Comercio: "Shop FT",
            CUIT: '32000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: false,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'214',
            Comercio: "Shop HJ",
            CUIT: '31000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 540,
            Activo: true,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'215',
            Comercio: "Shop KI",
            CUIT: '50030000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 99,
            Activo: true,
            UltimaVenta: '02/02/1995'
        },
        {
            ID:'216',
            Comercio: "Shop WE",
            CUIT: '80100000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1001,
            Activo: true,
            UltimaVenta: '21/12/1995'
        },
        {
            ID:'217',
            Comercio: "Shop CC",
            CUIT: '69000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: false,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'218',
            Comercio: "Shop PP",
            CUIT: '10300000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 3200,
            Activo: false,
            UltimaVenta: '11/11/1995'
        },
        {
            ID:'219',
            Comercio: "Shop JJ",
            CUIT: '50000003',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 91,
            Activo: true,
            UltimaVenta: '21/02/1995'
        },
        {
            ID:'220',
            Comercio: "Comercio R",
            CUIT: '54100000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 12,
            Activo: false,
            UltimaVenta: '28/03/1995'
        },
        {
            ID:'221',
            Comercio: "Comercio A",
            CUIT: '50008000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 90,
            Activo: true,
            UltimaVenta: '02/09/1995'
        },
        {
            ID:'222',
            Comercio: "Alocado S",
            CUIT: '50160000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 789,
            Activo: true,
            UltimaVenta: '16/04/1995'
        },
        {
            ID:'223',
            Comercio: "Barcelona FC",
            CUIT: '50000120',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: true,
            UltimaVenta: '21/04/1995'
        },
        {
            ID:'224',
            Comercio: "PSG",
            CUIT: '20100000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 400,
            Activo: true,
            UltimaVenta: '10/10/1995'
        },
        {
            ID:'225',
            Comercio: "Real Madrid FC",
            CUIT: '56150000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: true,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'226',
            Comercio: "Chelsea FC",
            CUIT: '50000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 100000,
            Activo: false,
            UltimaVenta: '18/09/1995'
        },
        {
            ID:'227',
            Comercio: "Boca Juniors CA",
            CUIT: '23000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: true,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'228',
            Comercio: "Independiente CA",
            CUIT: '50007200',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 12,
            Activo: true,
            UltimaVenta: '11/03/1995'
        },
        {
            ID:'229',
            Comercio: "Juan Juniors CA",
            CUIT: '50029000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: false,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'230',
            Comercio: "Cristiano Ronaldo",
            CUIT: '20000010',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: false,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'231',
            Comercio: "Carlitos Shop",
            CUIT: '10012000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 10000,
            Activo: true,
            UltimaVenta: '21/09/1995'
        }],
        Data: [{
            ID:'200',
            Comercio: "Shop 200",
            CUIT: '60000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 209,
            Activo: false,
            UltimaVenta: '14/09/1995'
        },
        {
            ID:'202',
            Comercio: "Shop NW",
            CUIT: '10000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 450,
            Activo: false,
            UltimaVenta: '25/02/1995'
        },
        {
            ID:'204',
            Comercio: "Shop XA",
            CUIT: '30000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 605,
            Activo: true,
            UltimaVenta: '4/08/1995'
        },
        {
            ID:'203',
            Comercio: "Shop EW",
            CUIT: '40000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 540,
            Activo: true,
            UltimaVenta: '22/01/1995'
        },
        {
            ID:'205',
            Comercio: "Shop PO",
            CUIT: '52200000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 2300,
            Activo: false,
            UltimaVenta: '11/02/1994'
        },
        {
            ID:'206',
            Comercio: "Shop FD",
            CUIT: '70000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 986,
            Activo: true,
            UltimaVenta: '23/11/1995'
        },
        {
            ID:'207',
            Comercio: "Shop CV",
            CUIT: '88000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1235,
            Activo: true,
            UltimaVenta: '21/07/1995'
        },
        {
            ID:'208',
            Comercio: "Shop LK",
            CUIT: '95000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 732,
            Activo: true,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'209',
            Comercio: "Shop QW",
            CUIT: '50001100',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 913,
            Activo: true,
            UltimaVenta: '01/09/1995'
        },
        {
            ID:'210',
            Comercio: "Shop ZX",
            CUIT: '10040000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 543,
            Activo: false,
            UltimaVenta: '05/09/1995'
        },
        {
            ID:'211',
            Comercio: "Shop BG",
            CUIT: '20001000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 789,
            Activo: false,
            UltimaVenta: '21/01/1995'
        },
        {
            ID:'212',
            Comercio: "Shop RE",
            CUIT: '71000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 111,
            Activo: true,
            UltimaVenta: '08/08/1998'
        },
        {
            ID:'213',
            Comercio: "Shop FT",
            CUIT: '32000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: false,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'214',
            Comercio: "Shop HJ",
            CUIT: '31000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 540,
            Activo: true,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'215',
            Comercio: "Shop KI",
            CUIT: '50030000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 99,
            Activo: true,
            UltimaVenta: '02/02/1995'
        },
        {
            ID:'216',
            Comercio: "Shop WE",
            CUIT: '80100000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1001,
            Activo: true,
            UltimaVenta: '21/12/1995'
        },
        {
            ID:'217',
            Comercio: "Shop CC",
            CUIT: '69000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: false,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'218',
            Comercio: "Shop PP",
            CUIT: '10300000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 3200,
            Activo: false,
            UltimaVenta: '11/11/1995'
        },
        {
            ID:'219',
            Comercio: "Shop JJ",
            CUIT: '50000003',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 91,
            Activo: true,
            UltimaVenta: '21/02/1995'
        },
        {
            ID:'220',
            Comercio: "Comercio R",
            CUIT: '54100000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 12,
            Activo: false,
            UltimaVenta: '28/03/1995'
        },
        {
            ID:'221',
            Comercio: "Comercio A",
            CUIT: '50008000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 90,
            Activo: true,
            UltimaVenta: '02/09/1995'
        },
        {
            ID:'222',
            Comercio: "Alocado S",
            CUIT: '50160000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 789,
            Activo: true,
            UltimaVenta: '16/04/1995'
        },
        {
            ID:'223',
            Comercio: "Barcelona FC",
            CUIT: '50000120',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: true,
            UltimaVenta: '21/04/1995'
        },
        {
            ID:'224',
            Comercio: "PSG",
            CUIT: '20100000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 400,
            Activo: true,
            UltimaVenta: '10/10/1995'
        },
        {
            ID:'225',
            Comercio: "Real Madrid FC",
            CUIT: '56150000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: true,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'226',
            Comercio: "Chelsea FC",
            CUIT: '50000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 100000,
            Activo: false,
            UltimaVenta: '18/09/1995'
        },
        {
            ID:'227',
            Comercio: "Boca Juniors CA",
            CUIT: '23000000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: true,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'228',
            Comercio: "Independiente CA",
            CUIT: '50007200',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 12,
            Activo: true,
            UltimaVenta: '11/03/1995'
        },
        {
            ID:'229',
            Comercio: "Juan Juniors CA",
            CUIT: '50029000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: false,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'230',
            Comercio: "Cristiano Ronaldo",
            CUIT: '20000010',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 1000,
            Activo: false,
            UltimaVenta: '21/09/1995'
        },
        {
            ID:'231',
            Comercio: "Carlitos Shop",
            CUIT: '10012000',
            Concepto1: 1,
            Concepto2: 1,
            Concepto3: 1,
            Concepto4: 1,
            Concepto5: 1,
            Concepto6: 1,
            BalanceAnual: 10000,
            Activo: true,
            UltimaVenta: '21/09/1995'
        }]
    };

    return async function(dispatch){
        if(filter){
            console.log(`https://api.koibanx.com/stores?q={"$or": [{"ID": ${filter}}, {"CUIT": ${filter}}, {"Comercio": ${filter}}]}`)
            const dataFiltered = await state.Data.filter(el => el.ID.includes(filter) || el.CUIT.includes(filter) || el.Comercio.toLowerCase().includes(filter.toLowerCase()))

            return dispatch({
                type: 'GET_DATA',
                payload: dataFiltered
            })
        }
        else{
            console.log(`https://api.koibanx.com/stores`)

            return dispatch({
                type: 'GET_DATA',
                payload: state.Data
            })
        }
    }
}

export function orderByCUIT(payload){
    return{
        type: 'ORDER_BY_CUIT',
        payload
    }
}

export function orderByComercios(payload){
    return{
        type: 'ORDER_BY_COMERCIOS',
        payload
    }
}

export function filterByActivo(payload){
    return{
        type: 'FILTER_ACTIVO',
        payload
    }
}